const uncaughtException = (err) => {
    console.log(err.name, err.message);

    console.log('UNHANDLED EXCEPTION! ðŸ’¥ Shutting down...');
    process.exit(1);
};

module.exports = uncaughtException;
